# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
# - board: nice_nano_v2
#    shield: corne_left
# - board: nice_nano_v2 
#    shield: corne_right



# corne
  - board: seeeduino_xiao_ble
    shield: corne_dongle dongle_display
    artifact-name: corne_dongle
  - board: nice_nano_v2
    shield: corne_left_central
    artifact-name: corne_left_central
  - board: nice_nano_v2
    shield: corne_left_peripheral
    artifact-name: corne_left_peripheral
  - board: nice_nano_v2
    shield: corne_right_peripheral
    artifact-name: corne_right_peripheral
    
  - board: seeeduino_xiao_ble
    shield: corne_dongle dongle_display
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: corne_dongle_with_logging

    # reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset