
include:
# - board: nice_nano_v2
#    shield: corne_left
# - board: nice_nano_v2 
#    shield: corne_right



# corne
  - board: seeeduino_xiao_ble
    shield: corne_dongle dongle_display
    artifact-name: corne_dongle
  - board: nice_nano
    shield: corne_left_central
    artifact-name: corne_left_central
  - board: nice_nano
    shield: corne_left_peripheral
    artifact-name: corne_left_peripheral
  - board: nice_nano
    shield: corne_right_peripheral
    artifact-name: corne_right_peripheral
    
# - board: seeeduino_xiao_ble
 #   shield: corne_dongle dongle_display
 #   cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
  #  artifact-name: corne_dongle_with_logging

    # reset
#  - board: seeeduino_xiao_ble
#    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
