
include:

    # nice
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Corne_View\"
    artifact-name: nice_corne_left
    # shield: corne_left # for OLED no nice_view
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    artifact-name: nice_corne_right
    # shield: corne_right # for OLED no nice_view

    # puchi
  - board: puchi_ble_v1
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Puchi_Corne_View\"
    artifact-name: puchi_corne_left
    # shield: corne_left # for OLED no nice_view
  - board: puchi_ble_v1
    shield: corne_right nice_view_adapter nice_view
    artifact-name: puchi_corne_right
    # shield: corne_right # for OLED no nice_view

    # peripheral_left
  - board: nice_nano_v2
    shield: corne_left_peripheral nice_view_adapter nice_view
    artifact-name: nice_corne_left_peripheral
  - board: puchi_ble_v1
    shield: corne_left_peripheral nice_view_adapter nice_view
    artifact-name: puchi_corne_left_peripheral

    # ProMicro_Dongle
  - board: nice_nano_v2
    shield: corne_dongle_pro_micro
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Dongle\"
    artifact-name: nice_corne_dongle_pro_micro
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: corne_dongle_pro_micro dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Dongle_O\"
    artifact-name: nice_corne_dongle_pro_micro_dongle_display
    snippet: zmk-usb-logging
  - board: puchi_ble_v1
    shield: corne_dongle_pro_micro
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Puchi_Dongle\"
    artifact-name: puchi_corne_dongle_pro_micro
    snippet: zmk-usb-logging
  - board: puchi_ble_v1
    shield: corne_dongle_pro_micro dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Puchi_Dongle_O\"
    artifact-name: puchi_corne_dongle_pro_micro_dongle_display
    snippet: zmk-usb-logging

    # settings_reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_settings_reset
  - board: puchi_ble_v1
    shield: settings_reset
    artifact-name: puchi_settings_reset
